
package com.gus.rbczs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* EcooperationWebServiceService service = new EcooperationWebServiceService();
* EcooperationWebService portType = service.getEcooperationWebServicePort();
* portType.shortInsureService(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "EcooperationWebServiceService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", wsdlLocation = "http://www.epicc.com.cn/ecooperation/webservice/insure?wsdl")
public class EcooperationWebServiceService extends Service {

	private final static URL ECOOPERATIONWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.gus.rbczs.EcooperationWebServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.gus.rbczs.EcooperationWebServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://www.epicc.com.cn/ecooperation/webservice/insure?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://www.epicc.com.cn/ecooperation/webservice/insure?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ECOOPERATIONWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public EcooperationWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public EcooperationWebServiceService() {
		super(ECOOPERATIONWEBSERVICESERVICE_WSDL_LOCATION,
				new QName("http://webservice.ecooperation.epicc.com.cn/", "EcooperationWebServiceService"));
	}

	/**
	 * 
	 * @return returns EcooperationWebService
	 */
	@WebEndpoint(name = "EcooperationWebServicePort")
	public EcooperationWebService getEcooperationWebServicePort() {
		return super.getPort(new QName("http://webservice.ecooperation.epicc.com.cn/", "EcooperationWebServicePort"),
				EcooperationWebService.class);
	}

}
