
package com.gus.db;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CommServerWebServicePortType", targetNamespace = "http://webservice.web.agent.application.sinosoft.com")
public interface CommServerWebServicePortType {

	/**
	 * 
	 * @param in0
	 * @param in1
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.web.agent.application.sinosoft.com")
	@RequestWrapper(localName = "batchPolicyService", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.BatchPolicyService")
	@ResponseWrapper(localName = "batchPolicyServiceResponse", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.BatchPolicyServiceResponse")
	public String batchPolicyService(
			@WebParam(name = "in0", targetNamespace = "http://webservice.web.agent.application.sinosoft.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://webservice.web.agent.application.sinosoft.com") String in1);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.web.agent.application.sinosoft.com")
	@RequestWrapper(localName = "checkDataService", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.CheckDataService")
	@ResponseWrapper(localName = "checkDataServiceResponse", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.CheckDataServiceResponse")
	public String checkDataService(
			@WebParam(name = "in0", targetNamespace = "http://webservice.web.agent.application.sinosoft.com") String in0);

	/**
	 * 
	 * @param in0
	 * @param in1
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.web.agent.application.sinosoft.com")
	@RequestWrapper(localName = "generatePolicyService", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.GeneratePolicyService")
	@ResponseWrapper(localName = "generatePolicyServiceResponse", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.GeneratePolicyServiceResponse")
	public String generatePolicyService(
			@WebParam(name = "in0", targetNamespace = "http://webservice.web.agent.application.sinosoft.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://webservice.web.agent.application.sinosoft.com") String in1);

	/**
	 * 
	 * @param in0
	 * @param in1
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.web.agent.application.sinosoft.com")
	@RequestWrapper(localName = "withdrawPolicyService", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.WithdrawPolicyService")
	@ResponseWrapper(localName = "withdrawPolicyServiceResponse", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.WithdrawPolicyServiceResponse")
	public String withdrawPolicyService(
			@WebParam(name = "in0", targetNamespace = "http://webservice.web.agent.application.sinosoft.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://webservice.web.agent.application.sinosoft.com") String in1);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CCBPolicyService")
	@WebResult(name = "out", targetNamespace = "http://webservice.web.agent.application.sinosoft.com")
	@RequestWrapper(localName = "CCBPolicyService", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.CCBPolicyService")
	@ResponseWrapper(localName = "CCBPolicyServiceResponse", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", className = "com.gus.db.CCBPolicyServiceResponse")
	public String ccbPolicyService(
			@WebParam(name = "in0", targetNamespace = "http://webservice.web.agent.application.sinosoft.com") String in0);

}
