
package com.gus.db;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* CommServerWebService service = new CommServerWebService();
* CommServerWebServicePortType portType = service.getCommServerWebServiceHttpPort();
* portType.batchPolicyService(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "CommServerWebService", targetNamespace = "http://webservice.web.agent.application.sinosoft.com", wsdlLocation = "http://59.151.126.64:5555/eies/CommServerWebService.ws?wsdl")
public class CommServerWebService extends Service {

	private final static URL COMMSERVERWEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.gus.db.CommServerWebService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.gus.db.CommServerWebService.class.getResource(".");
			url = new URL(baseUrl, "http://59.151.126.64:5555/eies/CommServerWebService.ws?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://59.151.126.64:5555/eies/CommServerWebService.ws?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		COMMSERVERWEBSERVICE_WSDL_LOCATION = url;
	}

	public CommServerWebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CommServerWebService() {
		super(COMMSERVERWEBSERVICE_WSDL_LOCATION,
				new QName("http://webservice.web.agent.application.sinosoft.com", "CommServerWebService"));
	}

	/**
	 * 
	 * @return returns CommServerWebServicePortType
	 */
	@WebEndpoint(name = "CommServerWebServiceHttpPort")
	public CommServerWebServicePortType getCommServerWebServiceHttpPort() {
		return super.getPort(
				new QName("http://webservice.web.agent.application.sinosoft.com", "CommServerWebServiceHttpPort"),
				CommServerWebServicePortType.class);
	}

}
