
package com.gus.rbj.tb;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RevokePolicyPortType", targetNamespace = "http://services.ws.lis.sinosoft.com")
public interface RevokePolicyPortType {

	/**
	 * 
	 * @param printNo
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "urn:deleteContSend")
	@WebResult(targetNamespace = "http://services.ws.lis.sinosoft.com")
	@RequestWrapper(localName = "deleteContSend", targetNamespace = "http://services.ws.lis.sinosoft.com", className = "com.gus.rbj.tb.DeleteContSend")
	@ResponseWrapper(localName = "deleteContSendResponse", targetNamespace = "http://services.ws.lis.sinosoft.com", className = "com.gus.rbj.tb.DeleteContSendResponse")
	public String deleteContSend(
			@WebParam(name = "printNo", targetNamespace = "http://services.ws.lis.sinosoft.com") String printNo);

	/**
	 * 
	 * @param args
	 */
	@WebMethod(action = "urn:main")
	@Oneway
	@RequestWrapper(localName = "main", targetNamespace = "http://services.ws.lis.sinosoft.com", className = "com.gus.rbj.tb.Main")
	public void main(
			@WebParam(name = "args", targetNamespace = "http://services.ws.lis.sinosoft.com") List<String> args);

	/**
	 * 
	 * @param printno
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "urn:deleteCont1")
	@WebResult(targetNamespace = "http://services.ws.lis.sinosoft.com")
	@RequestWrapper(localName = "deleteCont1", targetNamespace = "http://services.ws.lis.sinosoft.com", className = "com.gus.rbj.tb.DeleteCont1")
	@ResponseWrapper(localName = "deleteCont1Response", targetNamespace = "http://services.ws.lis.sinosoft.com", className = "com.gus.rbj.tb.DeleteCont1Response")
	public String deleteCont1(
			@WebParam(name = "printno", targetNamespace = "http://services.ws.lis.sinosoft.com") String printno);

	/**
	 * 
	 * @param xmlData
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "urn:service")
	@WebResult(targetNamespace = "http://services.ws.lis.sinosoft.com")
	@RequestWrapper(localName = "service", targetNamespace = "http://services.ws.lis.sinosoft.com", className = "com.gus.rbj.tb.Service")
	@ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://services.ws.lis.sinosoft.com", className = "com.gus.rbj.tb.ServiceResponse")
	public String service(
			@WebParam(name = "xmlData", targetNamespace = "http://services.ws.lis.sinosoft.com") String xmlData);

}
