
package com.gus.rbj.tb;


import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingType;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* RevokePolicy service = new RevokePolicy();
* RevokePolicyPortType portType = service.getRevokePolicyHttpSoap11Endpoint();
* portType.deleteContSend(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "RevokePolicy", targetNamespace = "http://services.ws.lis.sinosoft.com", wsdlLocation = "http://114.255.117.76:8083/lalala/services/RevokePolicy?wsdl")
@BindingType(value=SOAPBinding.SOAP12HTTP_BINDING)
public class RevokePolicy extends Service {

	private final static URL REVOKEPOLICY_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.gus.rbj.tb.RevokePolicy.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.gus.rbj.tb.RevokePolicy.class.getResource(".");
			url = new URL(baseUrl, "http://114.255.117.76:8083/lalala/services/RevokePolicy?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://114.255.117.76:8083/lalala/services/RevokePolicy?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		REVOKEPOLICY_WSDL_LOCATION = url;
	}

	public RevokePolicy(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RevokePolicy() {
		super(REVOKEPOLICY_WSDL_LOCATION, new QName("http://services.ws.lis.sinosoft.com", "RevokePolicy"));
	}

	/**
	 * 
	 * @return returns RevokePolicyPortType
	 */
	@WebEndpoint(name = "RevokePolicyHttpSoap11Endpoint")
	public RevokePolicyPortType getRevokePolicyHttpSoap11Endpoint() {
		return super.getPort(new QName("http://services.ws.lis.sinosoft.com", "RevokePolicyHttpSoap11Endpoint"),
				RevokePolicyPortType.class);
	}

	/**
	 * 
	 * @return returns RevokePolicyPortType
	 */
	@WebEndpoint(name = "RevokePolicyHttpSoap12Endpoint")
	public RevokePolicyPortType getRevokePolicyHttpSoap12Endpoint() {
		return super.getPort(new QName("http://services.ws.lis.sinosoft.com", "RevokePolicyHttpSoap12Endpoint"),
				RevokePolicyPortType.class);
	}

	/**
	 * 
	 * @return returns RevokePolicyPortType
	 */
	@WebEndpoint(name = "RevokePolicyHttpEndpoint")
	public RevokePolicyPortType getRevokePolicyHttpEndpoint() {
		return super.getPort(new QName("http://services.ws.lis.sinosoft.com", "RevokePolicyHttpEndpoint"),
				RevokePolicyPortType.class);
	}

}
