
package com.gus.rbc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EcooperationWebService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/")
public interface EcooperationWebService {

	/**
	 * 
	 * @param interfaceNo
	 * @param datas
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insureService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.InsureService")
	@ResponseWrapper(localName = "insureServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.InsureServiceResponse")
	public String insureService(@WebParam(name = "interfaceNo", targetNamespace = "") String interfaceNo,
			@WebParam(name = "datas", targetNamespace = "") String datas);

	/**
	 * 
	 * @param interfaceNo
	 * @param datas
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "printProofService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.PrintProofService")
	@ResponseWrapper(localName = "printProofServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.PrintProofServiceResponse")
	public String printProofService(@WebParam(name = "interfaceNo", targetNamespace = "") String interfaceNo,
			@WebParam(name = "datas", targetNamespace = "") String datas);

	/**
	 * 
	 * @param interfaceNo
	 * @param datas
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "modifyService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.ModifyService")
	@ResponseWrapper(localName = "modifyServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.ModifyServiceResponse")
	public String modifyService(@WebParam(name = "interfaceNo", targetNamespace = "") String interfaceNo,
			@WebParam(name = "datas", targetNamespace = "") String datas);

	/**
	 * 
	 * @param interfaceNo
	 * @param datas
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "transitService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.TransitService")
	@ResponseWrapper(localName = "transitServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.TransitServiceResponse")
	public String transitService(@WebParam(name = "interfaceNo", targetNamespace = "") String interfaceNo,
			@WebParam(name = "datas", targetNamespace = "") String datas);

	/**
	 * 
	 * @param interfaceNo
	 * @param datas
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "shortInsureService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.ShortInsureService")
	@ResponseWrapper(localName = "shortInsureServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.ShortInsureServiceResponse")
	public String shortInsureService(@WebParam(name = "interfaceNo", targetNamespace = "") String interfaceNo,
			@WebParam(name = "datas", targetNamespace = "") String datas);

	/**
	 * 
	 * @param interfaceNo
	 * @param datas
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "shortModifyService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.ShortModifyService")
	@ResponseWrapper(localName = "shortModifyServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.ShortModifyServiceResponse")
	public String shortModifyService(@WebParam(name = "interfaceNo", targetNamespace = "") String interfaceNo,
			@WebParam(name = "datas", targetNamespace = "") String datas);

}
