
package com.gus.rbc.print;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* PrintWebServiceService service = new PrintWebServiceService();
* PrintWebService portType = service.getPrintWebServicePort();
* portType.printPolicyService(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "PrintWebServiceService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", wsdlLocation = "http://partnertest.mypicc.com.cn/ecooperation/webservice/print?wsdl")
public class PrintWebServiceService extends Service {

	private final static URL PRINTWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.gus.rbc.print.PrintWebServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.gus.rbc.print.PrintWebServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://partnertest.mypicc.com.cn/ecooperation/webservice/print?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://partnertest.mypicc.com.cn/ecooperation/webservice/print?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PRINTWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public PrintWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PrintWebServiceService() {
		super(PRINTWEBSERVICESERVICE_WSDL_LOCATION,
				new QName("http://webservice.ecooperation.epicc.com.cn/", "PrintWebServiceService"));
	}

	/**
	 * 
	 * @return returns PrintWebService
	 */
	@WebEndpoint(name = "PrintWebServicePort")
	public PrintWebService getPrintWebServicePort() {
		return super.getPort(new QName("http://webservice.ecooperation.epicc.com.cn/", "PrintWebServicePort"),
				PrintWebService.class);
	}

}
