
package com.gus.rbc.print;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PrintWebService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/")
public interface PrintWebService {

	/**
	 * 
	 * @param interfaceNo
	 * @param datas
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "printPolicyService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.print.PrintPolicyService")
	@ResponseWrapper(localName = "printPolicyServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.gus.rbc.print.PrintPolicyServiceResponse")
	public String printPolicyService(@WebParam(name = "interfaceNo", targetNamespace = "") String interfaceNo,
			@WebParam(name = "datas", targetNamespace = "") String datas);

}
