package com.gus;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * EServerManageService service = new EServerManageService();
 * EServerManage portType = service.getEServerManage();
 * portType.getServerXML(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "EServerManageService", targetNamespace = "http://221.226.62.36:7002/prpall/services/EServerManage?wsdl")
public class EServerManageService extends Service {

	private final static URL ESERVERMANAGESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.gus.EServerManageService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.gus.EServerManageService.class.getResource(".");
			//http://221.226.62.36:7002/prpall/services/EServerManage?wsdl
			url = new URL(baseUrl,
					"http://221.226.62.36:7002/prpall/services/EServerManage?wsdl");
			
//			url = new URL(baseUrl,
//					"http://221.226.62.36:7002/prpall/services/EServerManage?wsdl");
			
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://221.226.62.36:7002/prpall/services/EServerManage?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ESERVERMANAGESERVICE_WSDL_LOCATION = url;
	}

	public EServerManageService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public EServerManageService() {
		super(
				ESERVERMANAGESERVICE_WSDL_LOCATION,
				new QName(
						"http://facade.servicerelease.servicecenter.prpall.sinosoft.com",
						"EServerManageService"));
	}

	/**
	 * 
	 * @return returns EServerManage
	 */
	@WebEndpoint(name = "EServerManage")
	public EServerManage getEServerManage() {
		return super
				.getPort(
						new QName(
								"http://facade.servicerelease.servicecenter.prpall.sinosoft.com",
								"EServerManage"), EServerManage.class);
	}

}
